Kokorin Ilya, HW 1
itmo2019/task1 pull request #1
Opened 2019-02-19 08:58 UTC by KokorinIlya

2019-02-22 10:24 UTC, KokorinIlya commented
<img width="1440" alt="2019-02-22 13 22 43" src="https://user-images.githubusercontent.com/26743496/53236365-259c1300-36a5-11e9-8cea-0305f9ce05c3.png">
<img width="1440" alt="2019-02-22 13 22 53" src="https://user-images.githubusercontent.com/26743496/53236377-2b91f400-36a5-11e9-8480-e06aa272663f.png">
<img width="1440" alt="2019-02-22 13 23 01" src="https://user-images.githubusercontent.com/26743496/53236382-2e8ce480-36a5-11e9-9950-adb7473610c8.png">

2019-02-22 10:25 UTC, KokorinIlya commented
Как-то так это выглядит

2019-02-25 13:58 UTC, rmbaad requested changes

2019-02-25 13:58 UTC, rmbaad commented on src/index.html
> +                    Для меня курс <span class="front">фронтенда</span> в первую очередь, возможность с необычной точки зрения посмотреть на все накопленные
Имя класса желательно должно отображать какую-то суть применения, он должен быть семантичным. Например, если есть класс `title`, сразу видно что это какой-то заголовок. Класс `front` не очень отражает свою суть. Я бы заменил его на что-то более подходящее, например `highlight`

2019-02-25 13:58 UTC, rmbaad commented on src/index.html
> +            <br>
`<br>` как правило используется для переносов внутри текста, для отступов между блоками лучше использовать стили

2019-02-25 13:58 UTC, rmbaad commented on src/index.html
> +        <main id="pictures-main">
Мелочь, но селекторы лучше писать в едином стиле, например присутствуют два вида: `final_list ` и `pictures-main`

2019-02-25 13:58 UTC, rmbaad commented on src/index.html
> +                <p id="contacts_field" class="contacts-part">Контакты</p>
Для чего часть сделана через id а часть через class? Кажется что здесь нет надобности в id. Как вариант можно сделать краткое содержание с ссылками вида `<a href="contacts">Контакты</a>` где-то вначале, а id которые используются для стилей унести в классы

2019-02-25 13:58 UTC, rmbaad commented on src/style.css
> +h2 {
Стили по имени тега — не очень хорошая практика. В данном случае не критично, но проблемы могут начаться, когда захочется использовать этот же тег в другом месте страницы с другими стилями. Стили лучше всегда назначать определённому классу

2019-02-25 13:58 UTC, rmbaad commented on src/style.css
> +    background-color: beige;
Если хочется больше цветов, их можно указывать через [HEX](https://ru.wikipedia.org/wiki/%D0%A8%D0%B5%D1%81%D1%82%D0%BD%D0%B0%D0%B4%D1%86%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D1%87%D0%BD%D0%B0%D1%8F_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0_%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F) (просто на будущее). Можно взять графический редактор или воспользоваться сервисами вроде http://getcolor.ru/ чтобы получить HEX для любого цвета и использовать как `color: #FA981E`. Так же можно использовать в формате rgba, где три числа это red, blue, green а четвёртое — прозрачность, например `background-color: rgba(255, 0, 255, 0.5)`

2019-02-25 19:22 UTC, KokorinIlya commented on src/index.html
> +                <p id="contacts_field" class="contacts-part">Контакты</p>
Ну смысл в том, чтобы вся информация в контактах подчёркивалась, но жирным выделялось только что-то одно

2019-02-25 19:23 UTC, KokorinIlya commented on src/style.css
> +    background-color: beige;
Да я знаю, просто цвета, которые намешивал я, были слишком вырвиглазные, решил пользоваться стандартными

2019-02-25 20:14 UTC, rmbaad approved these changes

2019-02-27 14:35 UTC, closed without merging