HW1 - Ваксман Денис M3339
itmo2019/task1 pull request #11
Opened 2019-02-23 00:59 UTC by DrDet

2019-02-27 14:37 UTC, trixartem requested changes

2019-02-27 14:37 UTC, trixartem commented on index.html
> +            <hr>
hr лучше добавлять внутрь текста, где есть разделение мысле

2019-02-27 14:37 UTC, trixartem commented on index.html
> +        <link rel="stylesheet" href="main.css">
не хватает тега про кодировке

2019-02-27 14:37 UTC, trixartem commented on main.css
> +    font-size: 14px;
шрифт можно схлопнуть в одно свойство

2019-02-27 14:37 UTC, trixartem commented on main.css
> +    text-indent: 2ch;
Отступы лучше всего указывать в px, поскольку эта величина часто используется в макетах с дизайном

2019-02-27 14:37 UTC, trixartem commented on main.css
> +    border-width: 1px;
Можно в одно свойство

2019-02-28 15:24 UTC, DrDet commented
Внесены правки.

2019-03-14 17:25 UTC, closed without merging