done
itmo2019/task1 pull request #12
Opened 2019-02-23 10:17 UTC by Recognized

2019-02-27 21:21 UTC, evgenymarkov requested changes

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +<html lang="en">
Документ содержит, в основном, русскоязычный контент, поэтому 

```html
<html lang="ru">
```

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +                <td style="background: #324053"></td>
inline стили лучше не использовать, их применяют крайне редко, чуть чаще – тэг style если хотят загрузить критически важный CSS, но в остальных случаях лучше писать стили в отдельном файле

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +        * {
Универсальный селектор лучше не использовать. Вероятно ты хотел применить стили только для `body`.

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +        .xx {
Классы, как и переменные в коде, нужно именовать осмысленно и как можно реже прибегать к сокращениям

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +            size: 16pt;
Рекомендую использовать единицы измерения в таком приоритете:

px > rem > em > всё остальное

Абсолютные значения более просты в понимании и отладке, комбинировать em и px в реальных проектах приходится практически никогда

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +        #footer-2 {
id для стилей лучше не использовать, оставь их для логики в JavaScript. Стилизовать что-либо рекомендую исключительно с помощью классов.

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +            text-decoration-color: aqua !important;
К !important лучше прибегать в последнюю очередь

2019-02-27 21:21 UTC, evgenymarkov commented on index.html
> +            border-color: black;
Цвета лучше записывать в hex представлении, в нижнем регистре и по возможности в сокращённой форме:

```
#fff
#f5f5dc
```

2019-02-28 16:13 UTC, Recognized commented on index.html
> +            text-decoration-color: aqua !important;
Без этого не работает

2019-03-01 08:42 UTC, closed without merging