Тельнов Сергей, M3335
itmo2019/task1 pull request #16
Opened 2019-02-23 13:15 UTC by SerTelnov

2019-02-27 21:09 UTC, evgenymarkov requested changes

2019-02-27 21:09 UTC, evgenymarkov commented on index.html
> +                Люблю классы и типизацию, поэтому очень боюсь <dfn id="prog_lang">JavaScript</dfn>.
Не бойся, будет TypeScript

2019-02-27 21:09 UTC, evgenymarkov commented on index.html
> +</html>
Хорошим тоном считается в конце каждого файла иметь одну пустую строку. Чтобы вручную за этим не следить, есть такая вещь как EditorConfig. Это плагин, который есть для любой популярной IDE. Его конфиг записывается в файл `.editorconfig`. Содержимое может быть примерно следующим:

```
root = true

[*]
charset = utf-8
indent_size = 2
end_of_line = lf
indent_style = space
max_line_length = 100
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

2019-02-27 21:09 UTC, evgenymarkov commented on styles.css
> +    background-color: ghostwhite;
Цвета лучше записывать в hex представлении, в нижнем регистре и по возможности в сокращённой форме:

```
#fff
#f5f5dc
```

2019-02-27 21:09 UTC, evgenymarkov commented on styles.css
> +#intro {
id для стилей лучше не использовать, оставь их для логики в JavaScript. Стилизовать что-либо рекомендую исключительно с помощью классов.

2019-02-27 21:09 UTC, evgenymarkov commented on styles.css
> +    line-height: 150%;
Рекомендую использовать единицы измерения в таком приоритете:

px > rem > em > всё остальное

Абсолютные значения более просты в понимании и отладке, комбинировать em и px в реальных проектах приходится практически никогда

2019-02-27 21:09 UTC, evgenymarkov commented on styles.css
> +    line-height: 150%;
% хорошо работают для относительного позиционирования или width/height, но для margin'ов, padding'ов, размеров текста уместнее взять px/rem/em.

2019-02-27 21:09 UTC, evgenymarkov commented on index.html
> +            <h2>Введение</h2>
Разве введение не должно иметь тот же уровень заголовка что и остальные части эссе?)

2019-02-27 21:09 UTC, evgenymarkov commented on index.html
> +<html>
Документ содержит, в основном, русскоязычный контент, поэтому 

```html
<html lang="ru">
```

2019-02-28 18:26 UTC, SerTelnov commented
fixed

2019-03-01 08:37 UTC, evgenymarkov approved these changes

2019-03-01 08:37 UTC, closed without merging