Куриленко Влад, М3337, задание 1
itmo2019/task1 pull request #18
Opened 2019-02-23 15:05 UTC by MadHypnofrog

2019-02-27 16:23 UTC, underoot requested changes
В целом хорошо, нужны указанные правки

2019-02-27 16:23 UTC, underoot commented on task1.html
> +        <link rel=stylesheet href=styles.css charset=utf-8>
Лучше везде использовать единый стиль — двухкавычечный

2019-02-27 16:23 UTC, underoot commented on task1.html
> +                <p id="centered"><center><-- Это тоже я, как ни странно. --></center>
Тег [`<center><...></center>`](https://devdocs.io/html/element/center) является устаревшим, поэтому следует использовать центрирование в CSS

2019-02-27 16:23 UTC, underoot commented on styles.css
> +    font-family: 'Arial';
В качестве альтернативы если такого шрифта нет, нужно указать шрифт без засечек

2019-02-27 16:23 UTC, underoot commented on task1.html
> +        <header id=head><center>Эссе на тему <b>"Что я жду от курса фронтэнда"</b></center></header>
Тег [`<center><...></center>`](https://devdocs.io/html/element/center) является устаревшим, поэтому следует использовать центрирование в CSS

2019-02-27 16:23 UTC, underoot commented on task1.html
> +                <p id="centered"><center><-- Это тоже я, как ни странно. --></center>
В данном случае тег `<p>` закроется до `<center>`. Зачем тогда здесь тег `<p>` с центрирующим модификатор, который ничего не центрирует?

2019-02-27 16:23 UTC, underoot commented on task1.html
> +            <div style="position: relative; width: 34%">
Как рекомендация — избегать инлайн-стилей

2019-02-27 16:23 UTC, underoot commented on styles.css
> +#golub {
Стиль голубя и уточки кажется немного одинаковым. Думаю, что можно объединить одним классом.

2019-02-28 05:28 UTC, MadHypnofrog commented on task1.html
> +        <link rel=stylesheet href=styles.css charset=utf-8>
поправил вроде везде, где было без кавычек

2019-02-28 05:30 UTC, MadHypnofrog commented on task1.html
> +                <p id="centered"><center><-- Это тоже я, как ни странно. --></center>
вынес в css

2019-02-28 05:32 UTC, MadHypnofrog commented on styles.css
> +    font-family: 'Arial';
добавил

2019-02-28 05:33 UTC, MadHypnofrog commented on task1.html
> +        <header id=head><center>Эссе на тему <b>"Что я жду от курса фронтэнда"</b></center></header>
вынес

2019-02-28 05:38 UTC, MadHypnofrog commented on task1.html
> +                <p id="centered"><center><-- Это тоже я, как ни странно. --></center>
кажется что этот p закроется вместе с div на следующей строке, center здесь точно центрировал фразу горизонтально между двумя изображениями
впрочем, сейчас эта центровка уже вынесена в css, поэтому неактуально

2019-02-28 05:41 UTC, MadHypnofrog commented on task1.html
> +            <div style="position: relative; width: 34%">
вынес в css, да

2019-02-28 05:56 UTC, MadHypnofrog commented on styles.css
> +#golub {
объединил

2019-02-28 22:14 UTC, underoot approved these changes

2019-02-28 22:14 UTC, closed without merging