add hw1
itmo2019/task1 pull request #28
Opened 2019-02-23 21:00 UTC by Tiloaria

2019-02-27 16:14 UTC, evgenymarkov requested changes

2019-02-27 16:14 UTC, evgenymarkov commented on HelloFrontend.html
> +<html lang="en">
Документ содержит, в основном, русскоязычный контент, поэтому 

```html
<html lang="ru">
```

2019-02-27 16:14 UTC, evgenymarkov commented on HelloFrontend.html
> +                    Прежде всего я открыла <strike>Yandex</strike> <a href="https://google.com">Google</a> и поискала чем фронтенд занимается подробнее. <br>
Рекомендуется вместо `strike` использовать CSS правило `text-decoration: line-through`

2019-02-27 16:14 UTC, evgenymarkov commented on HelloFrontend.html
> +    <article>
Вместо `article` больше подойдёт тэг `main`

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    display: flex;
`display: flex;` здесь кажется излишним

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    background-color: white;
Цвета лучше записывать в hex представлении, в нижнем регистре и по возможности в сокращённой форме:

```
#fff
#f5f5dc
```

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    animation-name: background-animation;
Для описания анимации лучше использовать [сокращённую форму](https://developer.mozilla.org/en-US/docs/Web/CSS/animation) записи

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    margin: 2em auto;
Рекомендую использовать единицы измерения в таком приоритете:

px > rem > em > всё остальное

Абсолютные значения более просты в понимании и отладке, комбинировать em и px в реальных проектах приходится практически никогда

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    justify-content: center;
`justify-content: center` будет работать только вместе с `display: flex`, это правило ни на что не влияет здесь.

2019-02-27 16:14 UTC, evgenymarkov commented on style.css
> +    opacity: 90%;
Лучше записать как `opacity: 0.9;`

2019-03-02 18:43 UTC, Tiloaria commented
@evgenymarkov все замечания исправлены.

2019-03-02 20:01 UTC, closed without merging