Виктория Ерохина, M3335
itmo2019/task1 pull request #3
Opened 2019-02-20 09:40 UTC by erokhinav

2019-02-25 12:02 UTC, underoot commented on src/index.html
> +					<hr noshade>
Если руководствоваться спецификации HTML5 (об использовании которой говорит [преамбула в начале файла](https://github.com/itmo2019/task1/blob/f1bd76a73878a6e4991fb230a1a0b5f935234f3e/src/index.html#L1)), то свойства `noshade` у элемента `hr` [нет](https://www.w3.org/TR/html52/grouping-content.html#the-hr-element). Еще в [версии спецификации HTML 4.01](https://www.w3.org/TR/html401/present/graphics.html#h-15.3) это свойства объявили _Deprecated_. Не стоит его использовать. Как вариант, написать стили для данного [атрибута самому](https://codepen.io/underoot/pen/wOwrxz)

2019-02-25 12:02 UTC, underoot commented on src/index.html
> +	<meta charset=utf-8>
Все-таки стоит использовать [_double quoted syntax_](https://www.w3.org/TR/html/syntax.html#elements-attributes) по нескольким причинам:
1.  Рано или поздно настанет момент, когда в верстке потребуется использовать значение атрибута с пробелами. Тогда придется использовать кавычки. Следует стремится к единообразию стиля, особенно если это касается разметки, поскольку чтение разметки, выполненного в однообразном стиле ускоряет чтение данной разметки в разы
2. HTML, конечно, не XML, но в целях соблюдения достаточной однообразности следует придерживаться XML-подобному синтаксису описания атрибутов.

2019-02-25 12:02 UTC, underoot commented on src/css/styles.css
> +span {
Какой-то очень обширный стиль, может уточнить его классом?

2019-02-25 15:13 UTC, underoot requested changes
По указанным замечаниям нужны правки

2019-02-26 08:20 UTC, erokhinav commented on src/index.html
> +					<hr noshade>
Спасибо! Добавила свой стиль.

2019-02-26 08:20 UTC, erokhinav commented on src/css/styles.css
> +span {
Задала стиль для псевдокласса :first-letter

2019-02-26 08:20 UTC, erokhinav commented
Замечания учтены.

2019-02-26 11:42 UTC, underoot approved these changes
В целом все хорошо! Остались только замечания, оставленные ниже. Особенно критичен комментарий про `!important`

2019-02-26 11:42 UTC, underoot commented on src/css/styles.css
> +	overflow-y: scroll;
А каково действия пыталась добиться? По-умолчанию, на область просмотра (_Viewport_) выставлено значение `overflow-y: visible`, что автоматически расценивается[<sup>1</sup>](#1) как `auto`.

<hr>

<a name="1">1.</a> [Данная спецификация](https://drafts.csswg.org/css-overflow-3/#overflow-propagation) черновик, но все браузеры ведут себя именно так.

2019-02-26 11:42 UTC, underoot commented on src/css/styles.css
> +    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
Тут проблемы с отступами

2019-02-26 11:42 UTC, underoot commented on src/css/styles.css
> +abbr {
`!important` — одна из самых плохих практик! Следует решить проблему уравниванием специфичности. Можно указать атрибут `title`
```suggestion
abbr[title] {
	text-decoration: none;
```

2019-02-26 11:42 UTC, underoot commented on src/css/styles.css
> +body {
В целом по файлу пляшут отступы. То табы, то пробелы. Стоит привести к одному виду

2019-02-26 11:55 UTC, erokhinav commented on src/css/styles.css
> +	overflow-y: scroll;
Удалила правило.

2019-02-26 11:56 UTC, erokhinav commented on src/css/styles.css
> +abbr {
Указала аттрибут `title`

2019-02-26 11:57 UTC, erokhinav commented
Fixed

2019-02-27 15:52 UTC, closed without merging