init0
itmo2019/task1 pull request #4
Opened 2019-02-20 20:13 UTC by Good-Morning

2019-02-27 15:02 UTC, trixartem requested changes
попробуй без js

2019-02-27 15:02 UTC, trixartem commented on file.html
> +<meta charset=UTF-8>
meta лучше держать в тегах head

2019-02-27 15:02 UTC, trixartem commented on file.html
> +                        <h3>Предисловие</h3><hr>
а где h1, h2?

2019-02-27 15:02 UTC, trixartem commented on file.html
> +                <button class=response onclick="report0()">
А как можно сделать без js?

2019-02-27 15:02 UTC, trixartem commented on file.html
> +                    <header onclick="fold1()">Чего я жду от курса</header>
больше тянет на заголовки h1, h2

2019-02-27 15:02 UTC, trixartem commented on file.html
> +                    <header onclick="fold2()">Еще текст</header>
Если это кликабельный элемент, давай поменяем курсор на подходящий?

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    padding-right: 0%;
Можно записывать одним свойством. если хочется занулить - можно просто поставить 0

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    font-size: 7pt;
Лучше в px или в em/rem

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    color: white;
#000

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    margin-right: inherit;
Можно схлопнуть в одно свойство

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    opacity: 0.0;
просто 0

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    opacity: 1.0;
просто 1

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +.item[state="open"] > .content {
Старайся по минимуму использовать атрибу, лучше сделать класс более уникальным

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    animation-timing-function: linear;
можно в одно свойство

2019-02-27 15:02 UTC, trixartem commented on rules.css
> +    font-family: 'Comic Sans';
нужен фолбэк, на случай, если не будет шрифта локально

2019-03-01 20:31 UTC, Good-Morning commented
Убрать js не вышло.

2019-03-14 17:29 UTC, closed without merging