Никита Дугинец M3337 Task1
itmo2019/task1 pull request #6
Opened 2019-02-21 21:09 UTC by glcanvas

2019-02-25 14:03 UTC, underoot commented on index.html
> +<html lang="en">
На вид, содержимое страницы всё-таки на русском

2019-02-25 14:03 UTC, underoot commented on index.html
> +                <ins>СSS</ins>
Почему это `ins`? [Согласно спецификации](https://www.w3.org/TR/html50/edits.html#the-ins-element) данный элемент представляет собой 

> The ins element represents an addition to the document.

, т. е. некий фрагмент текста, который был дополнительно добавлен. Здесь явно у этого слова семантика иная. Это скорее термин, или аббревиатура.

2019-02-25 14:03 UTC, underoot commented on index.html
> +                <i class="hard-i"><abbr title="Теория сложности">сложностью</abbr></i>
Не похоже на аббревиатуру или акроним

2019-02-25 14:03 UTC, underoot commented on index.html
> +                . <br>
Зачем `<br/>` если есть параграф

2019-02-25 14:03 UTC, underoot commented on index.html
> +<nav id="content">
А зачем тут идентификатор?

2019-02-25 14:03 UTC, underoot commented on index.html
> +        <span class="add-offset">Курс
Отступы бы пофиксить

2019-02-25 14:03 UTC, underoot commented on index.html
> +                <span class="add-offset">В заключении</span> хотелось бы написать какие теги были использованы:
Параграфам можно выставить отступ первой линии с помощью свойства `text-indent`. Например [вот так](https://codepen.io/underoot/pen/WmeBNb)

2019-02-25 15:14 UTC, underoot requested changes
По указанным замечаниям нужны правки

2019-03-01 15:50 UTC, glcanvas commented on index.html
> +        <span class="add-offset">Курс
что с ними? Идея говорит, что код отформатирован хорошо.

2019-03-01 15:55 UTC, underoot commented on index.html
> +        <span class="add-offset">Курс
`span`, [находится в коде](https://github.com/itmo2019/task1/blob/cc4107149954857a5ff71cacb2c370593c504977/index.html#L28) на уровне с родителем-`div`-ом. Не критично, разумеется, но читать сложно.

2019-03-01 16:10 UTC, glcanvas commented
@underoot поправил

2019-03-01 19:02 UTC, underoot commented on index.html
> +                <span class="add-offset">Так же</span> было бы здорово узнать много нового про
Кажется этот класс теперь лишний

2019-03-01 20:19 UTC, glcanvas commented on index.html
> +                <span class="add-offset">Так же</span> было бы здорово узнать много нового про
@underoot  учёл, поправил замечание

2019-03-01 21:54 UTC, underoot approved these changes

2019-03-01 21:54 UTC, closed without merging